### ISSUE TITLE
Choix du compte pour chiffre d'affaire: consolidé vs. complet

### ISSUE THREAD

**Issue by CharlesGaydon** [phe-sto/enthic#1]
L'API requeté avec un SIREN donné renvoie parfois plusieurs comptes annuels: N complet et parfois 1 consolidé. 

Pour TOTAL SA (SIREN 542051180), le CA "compte annuel consolidé" vaut bien 209.4 milliards comme attendu. Un CA "Compte annuel complet" est aussi renvoyé, qui vaut 7.377 milliards d'euros.

Pour ORAN (SIREN 330956871), seul une valeur de "Compte annuel complet" est renvoyée, qui ne correspond pas au chiffre d'affaire attendu de 3.623 pour l'année 2017 ([source](https://www.orano.group/docs/default-source/orano-doc/finance/publications-financieres-et-reglementees/2018/resultats-annuels-2018/orano_comptes-consolides_31122018.pdf?sfvrsn=e8b5c416_6)).

Données pour ORANO:

```
import requests
from pprint import pprint

response = requests.get("http://api.enthic.fr/company/siren/330956871/2018/").json()
pprint(response["financial_data"][21])
print("{} is {} billions € instead of 3.623 \n ".format(121086000.0, 121086000.0/(10**9)))
pprint(response)
```
Qui donne pour résultat:

![image](https://user-images.githubusercontent.com/11660435/78054191-f8c72e80-7381-11ea-9e96-432b9b11b6c4.png)

**Quelle valeur  accorder au CA du "Compte annuel complet" quand un CA pour le "Compte annuel consolidé" n'est pas présent ?**

**Comment by phe-sto** [comment]
Je pense comprendre la question. A la vue de leurs déclarations je n'accorderai pas grande valeur à ces chiffres. Les système des impôts Français semble trop compliqué pour la plupart d'entre nous.
Pour le group ORAN, pour 2016 en consolidé le CA est de 4k€+ j'ai l'impression qu'ils ont déclaré en millions directement (j'espère le faire un jour aussi ;) en 2017 un consolidé qui a l'air normal en 2018 pas de consolidé... C'est peut-être une erreur de saisie, il y en a énormement.
Votre document n'indique pas le siren, beaucoup de groupe déclare une société d'activité de siège qui elle seule déclare le consolidé. On est sûr que le group ORANO n'a pas créé une autre société?

**Comment by CharlesGaydon** [comment]
Effectivement ce doit être une question d'autre sociétés, car pour le siren renseigné dans la requête pour ORANO, je trouve des [sources@(https://www.societe.com/societe/orano-330956871.html) indiquant le chiffre renvoyé par l'API: 121 086 000.00 €.
Mais le chiffre consensus sur internet est plutôt de l'ordre de 3.6 milliards d'euros. DOnc j'imagine qu'il est divisé en plusieurs companies, et que le chiffre de 121M est celui de la holding.
Ca ne posera pas de problème pour mon usage à priori... Mais ça illustre la complexité d'agréger de rendre lisible ce type de données !
