### ISSUE TITLE
Is sh/database-creations.sh still compatible with recent MySQL 8 versions

### ISSUE THREAD

**Issue by phe-sto** [phe-sto/enthic#19]
I had to replace all `"$1"` by `--password="$1";` on my machine that as a quite recent version of MySQL 8.
Version is:
`mysql  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))`
Is it more safe in all case to have `--password="$1"` in sql commands?
I cannot recall why we just had `"$1"` do you? I just guess it was working fine older version of MySQL 8.

**Comment by leonarf** [comment]
If I recall correctly, I didn't modify the way we pass password to sql command. For what it worth, I prefer having "--password=" written than it being implicite. I think it's easier to understand. But I cannot say if it's safer or not.

**Comment by phe-sto** [comment]
That is what I recall too. We will have to create a PR.
