### ISSUE TITLE
New metadata file make the `clear_data.sh` script crash

### ISSUE THREAD

**Issue by phe-sto** [phe-sto/enthic#20]
Launching  `clear_data.sh` I get the following error message:
`[sudo] password for chrichri: 
STEP 1: REMOVE UNNECESSARY MD5 FILES IN ../input
STEP 2: UNZIPING IN ../input
Traceback (most recent call last):
  File "../python/enthic/extract_bundle.py", line 229, in <module>
    main()  # ONLY IF EXECUTED NOT WHEN IMPORTED
  File "../python/enthic/extract_bundle.py", line 182, in main
    "\t".join(
TypeError: sequence item 4: expected str instance, NoneType found
`
This ouput is self explanatory I guess.

**Comment by leonarf** [comment]
The output is self explanatory indeed, but I couldn't reproduce on my machine because I don't know which input file made it crash. The PR #22 is an almost blind try to fix it, but if there is other crash like that, please fill in the INPI daily zip name to use to reproduce.
Thank you :-)

**Comment by phe-sto** [comment]
The all data from the INPI from 2017 till end of 2020. The image of the production as it should be.

**Comment by phe-sto** [comment]
I think this issue can be closed once the PR https://github.com/phe-sto/enthic/pull/28 is merge.
