### ISSUE TITLE
L'entreprise 538348525 a ses chiffres multipliés par 2 en 2018

### ISSUE THREAD

**Issue by leonarf** [phe-sto/enthic#38]
Si on compare, par exemple, le chiffre d'affaire de cette entreprise dans Enthic (https://enthic-dataviz.netlify.app/entreprises/538348525) et sur LegalTile (https://www.legaltile.com/entreprise/beausejour-538348525/bilans/2199685), on voit que le notre est doublé.
Je pense que c'est parce que cette entreprise a livré ses comptes de 2018 deux fois, et donc ils apparaissent 2 fois dans les données brutes de l'INPI et qu'Enthic additionne les valeurs dans ce cas-là, ce qui est une erreur. Il faudrait prendre la 2ème version, ou ne garder que la première, ou encore faire une vérification plus compliquée, mais surtout pas additionner les valeurs, car on se retrouve avec des chiffres faux dans la base.

**Comment by phe-sto** [comment]
Est-ce que ça te vas si on se dit que l'on garde le dernier? Focntionnellement c'est une données plus à jour et la requête est légèrement plus simple.

**Comment by leonarf** [comment]
Ça me va oui :-)

**Comment by phe-sto** [comment]
Thank you very much @leonarf for helping in solving this old pain point. I just pushed a version into master that fixes this issue.
